name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # once per day

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployed app health
        uses: jakejarvis/url-health-check@v1
        with:
          url: https://full-stack-open-pokedex.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
