name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend
      - name: Install backend deps
        run: |
          cd backend
          npm install

      - name: Backend tests
        run: |
          cd backend
          npm test
        continue-on-error: true

      # Frontend
      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
